const StyleDictionary = require('style-dictionary');

// Custom format for CSS variables with theme support
StyleDictionary.registerFormat({
  name: 'css/theme-variables',
  format: function({ dictionary, options }) {
    const selector = options.selector || ':root';
    const tokens = dictionary.allTokens
      .map(token => `  --${token.name}: ${token.value};`)
      .join('\n');
    return `${selector} {\n${tokens}\n}\n`;
  }
});

// Custom format for TypeScript exports
StyleDictionary.registerFormat({
  name: 'typescript/es6-declarations',
  format: function({ dictionary }) {
    const tokens = dictionary.allTokens
      .map(token => {
        const name = token.name.replace(/-/g, '_').toUpperCase();
        return `export const ${name} = '${token.value}' as const;`;
      })
      .join('\n');

    const tokenMap = dictionary.allTokens
      .map(token => `  '${token.name}': '${token.value}'`)
      .join(',\n');

    return `// Auto-generated by Style Dictionary\n${tokens}\n\nexport const tokens = {\n${tokenMap}\n} as const;\n\nexport type TokenName = keyof typeof tokens;\n`;
  }
});

// Custom format for Tailwind preset
StyleDictionary.registerFormat({
  name: 'tailwind/preset',
  format: function({ dictionary }) {
    const colors = {};
    const spacing = {};
    const fontSize = {};
    const fontWeight = {};
    const fontFamily = {};
    const borderRadius = {};
    const boxShadow = {};
    const blur = {};
    const zIndex = {};
    const transitionDuration = {};
    const transitionTimingFunction = {};

    dictionary.allTokens.forEach(token => {
      const path = token.path;

      if (path[0] === 'color' && path[1] === 'primitive') {
        const colorName = path[2];
        const shade = path[3];
        if (!colors[colorName]) colors[colorName] = {};
        colors[colorName][shade || 'DEFAULT'] = token.value;
      }

      if (path[0] === 'spacing') {
        spacing[path[1]] = token.value;
      }

      if (path[0] === 'font') {
        if (path[1] === 'size') fontSize[path[2]] = token.value;
        if (path[1] === 'weight') fontWeight[path[2]] = token.value;
        if (path[1] === 'family') fontFamily[path[2]] = [token.value];
      }

      if (path[0] === 'radius') {
        borderRadius[path[1]] = token.value;
      }

      if (path[0] === 'shadow' && path.length === 2) {
        boxShadow[path[1]] = token.value;
      }

      if (path[0] === 'blur') {
        blur[path[1]] = token.value;
      }

      if (path[0] === 'zIndex') {
        zIndex[path[1]] = token.value;
      }

      if (path[0] === 'motion' && path[1] === 'duration') {
        transitionDuration[path[2]] = token.value;
      }

      if (path[0] === 'motion' && path[1] === 'easing') {
        transitionTimingFunction[path[2]] = token.value;
      }
    });

    const preset = {
      theme: {
        extend: {
          colors,
          spacing,
          fontSize,
          fontWeight,
          fontFamily,
          borderRadius,
          boxShadow,
          blur,
          zIndex,
          transitionDuration,
          transitionTimingFunction
        }
      }
    };

    return `// Auto-generated Tailwind preset by Style Dictionary
module.exports = ${JSON.stringify(preset, null, 2)};
`;
  }
});

// Custom transform for CSS variable names
StyleDictionary.registerTransform({
  name: 'name/cti/kebab-nested',
  type: 'name',
  transform: function(token) {
    return token.path.join('-');
  }
});

module.exports = {
  source: [
    'tokens/core/**/*.json',
    'tokens/semantic/**/*.json'
  ],
  platforms: {
    // Core CSS variables (theme-agnostic)
    css: {
      transformGroup: 'css',
      transforms: ['name/cti/kebab-nested', 'color/css'],
      buildPath: 'dist/css/',
      files: [{
        destination: 'tokens.css',
        format: 'css/theme-variables',
        options: {
          selector: ':root'
        }
      }]
    },

    // Dark theme CSS variables
    'css-dark': {
      transformGroup: 'css',
      transforms: ['name/cti/kebab-nested', 'color/css'],
      buildPath: 'dist/css/themes/',
      source: ['tokens/themes/dark.json'],
      files: [{
        destination: 'dark.css',
        format: 'css/theme-variables',
        options: {
          selector: '[data-theme="dark"], .dark'
        }
      }]
    },

    // Light theme CSS variables
    'css-light': {
      transformGroup: 'css',
      transforms: ['name/cti/kebab-nested', 'color/css'],
      buildPath: 'dist/css/themes/',
      source: ['tokens/themes/light.json'],
      files: [{
        destination: 'light.css',
        format: 'css/theme-variables',
        options: {
          selector: '[data-theme="light"], .light'
        }
      }]
    },

    // TypeScript exports
    ts: {
      transformGroup: 'js',
      transforms: ['name/cti/kebab-nested'],
      buildPath: 'dist/tokens/',
      files: [{
        destination: 'index.ts',
        format: 'typescript/es6-declarations'
      }]
    },

    // Tailwind preset
    tailwind: {
      transformGroup: 'js',
      buildPath: 'dist/tailwind/',
      files: [{
        destination: 'preset.js',
        format: 'tailwind/preset'
      }]
    },

    // JSON export (for Figma, etc.)
    json: {
      transformGroup: 'js',
      buildPath: 'dist/',
      files: [{
        destination: 'tokens.json',
        format: 'json/nested'
      }]
    }
  }
};
