import StyleDictionary from 'style-dictionary';

// Custom format for CSS variables with theme support
const cssThemeVariables = {
  name: 'css/theme-variables',
  format: function({ dictionary, options }) {
    const selector = options.selector || ':root';
    const tokens = dictionary.allTokens
      .map(token => `  --${token.name}: ${token.value};`)
      .join('\n');
    return `${selector} {\n${tokens}\n}\n`;
  }
};

// Custom format for TypeScript exports
const tsExports = {
  name: 'typescript/es6-declarations',
  format: function({ dictionary }) {
    const tokens = dictionary.allTokens
      .map(token => {
        const name = token.name.replace(/-/g, '_').toUpperCase();
        return `export const ${name} = '${token.value}' as const;`;
      })
      .join('\n');

    const tokenMap = dictionary.allTokens
      .map(token => `  '${token.name}': '${token.value}'`)
      .join(',\n');

    return `// Auto-generated by Style Dictionary\n${tokens}\n\nexport const tokens = {\n${tokenMap}\n} as const;\n\nexport type TokenName = keyof typeof tokens;\n`;
  }
};

// Custom format for Tailwind preset
const tailwindPreset = {
  name: 'tailwind/preset',
  format: function({ dictionary }) {
    const colors = {};
    const spacing = {};
    const fontSize = {};
    const fontWeight = {};
    const fontFamily = {};
    const borderRadius = {};
    const boxShadow = {};
    const blur = {};
    const zIndex = {};
    const transitionDuration = {};
    const transitionTimingFunction = {};
    const backgroundImage = {};
    const backdropBlur = {};

    dictionary.allTokens.forEach(token => {
      const path = token.path;

      if (path[0] === 'color' && path[1] === 'primitive') {
        const colorName = path[2];
        const shade = path[3];
        if (!colors[colorName]) colors[colorName] = {};
        colors[colorName][shade || 'DEFAULT'] = token.value;
      }

      if (path[0] === 'spacing') {
        spacing[path[1]] = token.value;
      }

      if (path[0] === 'font') {
        if (path[1] === 'size') fontSize[path[2]] = token.value;
        if (path[1] === 'weight') fontWeight[path[2]] = token.value;
        if (path[1] === 'family') fontFamily[path[2]] = [token.value];
      }

      if (path[0] === 'radius') {
        borderRadius[path[1]] = token.value;
      }

      if (path[0] === 'shadow' && path.length === 2) {
        boxShadow[path[1]] = token.value;
      }

      if (path[0] === 'blur') {
        blur[path[1]] = token.value;
      }

      if (path[0] === 'zIndex') {
        zIndex[path[1]] = token.value;
      }

      if (path[0] === 'motion' && path[1] === 'duration') {
        transitionDuration[path[2]] = token.value;
      }

      if (path[0] === 'motion' && path[1] === 'easing') {
        transitionTimingFunction[path[2]] = token.value;
      }

      // Gradients → backgroundImage
      if (path[0] === 'gradient') {
        const name = path.slice(1).join('-');
        backgroundImage[`gradient-${name}`] = token.value;
      }

      // Glass blur → backdropBlur
      if (path[0] === 'glass' && path[1] === 'blur') {
        backdropBlur[path[2]] = token.value;
      }
    });

    const preset = {
      theme: {
        extend: {
          colors,
          spacing,
          fontSize,
          fontWeight,
          fontFamily,
          borderRadius,
          boxShadow,
          blur,
          backdropBlur,
          backgroundImage,
          zIndex,
          transitionDuration,
          transitionTimingFunction
        }
      }
    };

    return `// Auto-generated Tailwind preset by Style Dictionary
module.exports = ${JSON.stringify(preset, null, 2)};
`;
  }
};

// Custom transform for CSS variable names
const kebabNestedTransform = {
  name: 'name/cti/kebab-nested',
  type: 'name',
  transform: function(token) {
    return token.path.join('-');
  }
};

// Shared hooks for all SD instances
const sharedHooks = {
  formats: {
    'css/theme-variables': cssThemeVariables.format,
    'typescript/es6-declarations': tsExports.format,
    'tailwind/preset': tailwindPreset.format,
  },
  transforms: {
    'name/cti/kebab-nested': kebabNestedTransform,
  }
};

const coreSources = [
  'tokens/core/**/*.json',
  'tokens/semantic/**/*.json'
];

// Core config — theme-agnostic tokens (tokens.css, tokens.json, TS, Tailwind)
const coreConfig = {
  hooks: sharedHooks,
  source: coreSources,
  platforms: {
    css: {
      transformGroup: 'css',
      transforms: ['name/cti/kebab-nested', 'color/css'],
      buildPath: 'dist/css/',
      files: [{
        destination: 'tokens.css',
        format: 'css/theme-variables',
        options: { selector: ':root' }
      }]
    },
    ts: {
      transformGroup: 'js',
      transforms: ['name/cti/kebab-nested'],
      buildPath: 'dist/tokens/',
      files: [{
        destination: 'index.ts',
        format: 'typescript/es6-declarations'
      }]
    },
    tailwind: {
      transformGroup: 'js',
      buildPath: 'dist/tailwind/',
      files: [{
        destination: 'preset.js',
        format: 'tailwind/preset'
      }]
    },
    json: {
      transformGroup: 'js',
      buildPath: 'dist/',
      files: [{
        destination: 'tokens.json',
        format: 'json/nested'
      }]
    }
  }
};

// Factory for theme configs — includes core sources for reference resolution,
// adds the theme file, and filters output to only --theme-* variables.
// SD v4.4.0 platform-level `source` does not add tokens to the dictionary,
// so we include theme files in the global source and use file-level filters.
function createThemeConfig(themeFile, selector, destination) {
  return {
    hooks: sharedHooks,
    source: [...coreSources, themeFile],
    platforms: {
      [`css-${destination.replace('.css', '')}`]: {
        transformGroup: 'css',
        transforms: ['name/cti/kebab-nested', 'color/css'],
        buildPath: 'dist/css/themes/',
        files: [{
          destination,
          format: 'css/theme-variables',
          options: { selector },
          filter: (token) => token.path[0] === 'theme',
        }]
      }
    }
  };
}

const darkConfig = createThemeConfig(
  'tokens/themes/dark.json',
  '[data-theme="dark"], .dark',
  'dark.css'
);

const lightConfig = createThemeConfig(
  'tokens/themes/light.json',
  '[data-theme="light"], .light',
  'light.css'
);

// Export all configs for programmatic build
export default coreConfig;
export { coreConfig, darkConfig, lightConfig };
